# Single dimension NumPy Array

In [2]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [2]:
type(n1)

numpy.ndarray

# MultiDimension NumPy array

In [3]:
import numpy as np
n2=np.array([[10,20,30,40],[10,80,90,20],[30,50,80,40],[1,2,3,4],[5,6,7,8]])
n2


array([[10, 20, 30, 40],
       [10, 80, 90, 20],
       [30, 50, 80, 40],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

# initilize NumPy array with zeros

In [4]:
n3=np.zeros((4,5))

In [5]:
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# initilization a array of matrix with full then 

In [6]:
n4=np.full((3,3),10)

In [7]:
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# initilization of NumPy array within a range.

In [8]:
n5=np.arange(10,30)

In [9]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

# initilization of the NumPy array with the skip numbers


In [12]:
n6=np.arange(1,20,3)

In [13]:
n6

array([ 1,  4,  7, 10, 13, 16, 19])

# initilization NumPy array with the random numbers


In [14]:
n7=np.random.randint(100000,1000000,1)

In [15]:
n7

array([192781])

# initilization the array shape changes in a fraction of seconds.

In [14]:
n8=np.array([[10,20,30],[10,80,90],[30,50,80],[30,50,80]])

In [15]:
n8

array([[10, 20, 30],
       [10, 80, 90],
       [30, 50, 80],
       [30, 50, 80]])

In [16]:
n8.shape

(4, 3)

In [17]:
n8.shape=(3,4)

In [18]:
n8

array([[10, 20, 30, 10],
       [80, 90, 30, 50],
       [80, 30, 50, 80]])

# joining NumPy array

In [19]:
import numpy as np

In [20]:
a=np.array([10,20,30])
b=np.array([30,50,90])

In [21]:
np.vstack((a,b))  #joining the numpy as vertical stacking 

array([[10, 20, 30],
       [30, 50, 90]])

In [22]:
np.hstack((a,b)) #joining numpy as horizontal stacking 

array([10, 20, 30, 30, 50, 90])

In [23]:
np.column_stack((a,b)) #joining numpy as column stacking

array([[10, 30],
       [20, 50],
       [30, 90]])

# NumPy intersection and difference

In [24]:
import numpy as np

In [25]:
x=np.array([10,20,30,40,50,60])

In [26]:
y=np.array([30,50,90,100,120,150])

In [27]:
np.intersect1d(x,y)

array([30, 50])

In [28]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

# Addition of NumPy Arrays

In [29]:
import numpy as np

In [30]:
t=np.array([10,20])
s=np.array([30,40])

In [31]:
np.sum([t,s])

100

In [32]:
np.sum([t,s],axis=0)

array([40, 60])

In [33]:
np.sum([t,s],axis=1)

array([30, 70])

# NumPy array mathematics


In [34]:
p=np.array([10,20,30])

In [35]:
p+1

array([11, 21, 31])

In [36]:
p/2

array([ 5., 10., 15.])

In [37]:
p*2

array([20, 40, 60])

In [38]:
p-2

array([ 8, 18, 28])

# Numpy maths functions

In [39]:
import numpy as np
nn=np.array([10,20,30,60])

In [40]:
np.mean(nn)

30.0

In [41]:
np.std(nn)

18.708286933869708

In [42]:
np.median(nn)

25.0

# saving and loading NumPy array

In [43]:
import numpy as np

In [44]:
n11=np.array([10,20,30,40,50])

In [45]:
np.save('my_name',n11) #saving the numpy array

In [46]:
np.load('my_name.npy') #loading the NumPy array.

array([10, 20, 30, 40, 50])